### ISSUE TITLE
Lighthouse Plugin : for cross cluster DNS resolution.

### ISSUE THREAD

**Issue by aswinsuryan** [openshift/coredns#27]
What would you like to be added: Lighthouse Plugin [1], which provides DNS resolution for services across clusters, as a default plugin in Openshift coreDNS

Why is this needed: 
Lighthouse plugin allows Cross Cluster Service Discovery between Kubernetes clusters connected by Submariner[2]. If the default Kubernetes plugin fails to resolve a DNS request, the lighthouse plugin will try to resolve it using the information it gathered from other clusters that have joined the submariner control plane. On a successful resolution, lighthouse plugin returns the cluster IP of the service in the remote cluster. Submariner ensures that this IP is reachable.

The the lighthouse plugin is now compiled as an external plugin and while deploying the openshift coreDNS image is updated by Submariner operator [3] by disabling Openshift CVO.

When lighthouse is made a default plugin,

1)if submariner is not deployed , it would return NXDOMAIN error
2)If submariner is deployed and a record was found , it would return a appropriate DNS record
3)If submariner is deployed and  the plugin is not able to resolve the request , it would return NXDOMAIN error

[1]https://github.com/submariner-io/lighthouse/tree/master/plugin/lighthouse
[2]https://github.com/submariner-io/submariner
[3]https://github.com/submariner-io/submariner-operator

**Comment by ironcladlou** [comment]
I wonder if the the same effect could be achieved without coupling to submariner itself.

The OpenShift [DNS forwarding API](https://github.com/openshift/enhancements/blob/master/enhancements/dns/plugins.md) explicitly disallows preempting our `kubernetes` plugin for `cluster.local` names. One option might be to introduce a generic cluster name delegation API which allows the administrator to specify a separate `forward` plugin configuration offered as a fallthrough to the`kubernetes` plugin. So the lookup chain would be:

lookup other-cluster.svc.cluster.local -> `kubernetes` plugin -> NXDOMAIN -> cluster `forward` plugin -> lighthouse DNS server

Would that solve this case as well as any other cluster name delegation scenarios?

**Comment by ironcladlou** [comment]
cc @openshift/sig-network-edge

**Comment by aswinsuryan** [comment]
We tried forward plugin approach but ran into a few issues, 

we had a DNSServer(based on coreDNS)  that runs within the cluster which had the information about services in a remote cluster that are connected. We wanted all the DNS request that the kubernetes plugin in coreDNS fails to resolve  to be sent to this in-cluster DNS server, which will try to resolve the request using the information it has about the remote clusters. If it succeeds then the record will be returned else it will return "Non-Existent Domain" error.

We wanted to use forward plugin to achieve this and we tried two configurations.(Since the configuration we require  are not supported by cluster-dns-operator we made the changes manually)

1) We added an entry in the default forward plugin configuration and made the policy as sequential.
The expectation was the requests that the Kubernetes plugin fails to resolve will be first sent to DNS Server that we run and if it fails will be resolved using /etc/resolv.conf. All though  discovery worked for remote services, the internet traffic did not work with this configuration.

  Corefile: |
    .:53 {
        errors
        health
        log
        kubernetes cluster2.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           #fallthrough in-addr.arpa ip6.arpa
           fallthrough
        }
        prometheus :9153
        forward . <DNS Server Service IP> /etc/resolv.conf {
            policy sequential
        }
        cache 30
        loop
        reload
        loadbalance
    }

2) Moved the  cluster2.local  from the default block and configured forward plugin. This worked for us, but we saw the resolution for internet traffic was taking significantly higher time.

  Corefile: |
    cluster2.local:53 {
        kubernetes cluster2.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           #fallthrough in-addr.arpa ip6.arpa
             fallthrough
        }
        forward .  <DNS Server Service IP>
    }
    .:53 {
        errors
        health
        log
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30

    }


Is there a better way to configure forward plugin for our use-case and avoid any kind of performance issue that we ran into.

**Comment by vthapar** [comment]
> The OpenShift [DNS forwarding API](https://github.com/openshift/enhancements/blob/master/enhancements/dns/plugins.md) explicitly disallows preempting our `kubernetes` plugin for `cluster.local` names

Lighthouse doesn't preempt 'kubernetes`. Only if `kubernetes` returns NXDOMAIN, we `fallthrough` to `lighthouse`.

**Comment by ironcladlou** [comment]
@aswinsuryan thank you for the detailed background... you may well be correct that the approach I described has some blocking issues in practice. I'm hoping me or someone on the team can do some more careful analysis and prototyping soon. Do you agree in principle that if the problems you found could be resolved that a generic forwarding to a separately managed Lighthouse DNS server would be reasonable?

To be clear, I'm not necessarily against the idea of carrying a patch for Lighthouse in-tree and then perhaps exposing some API to enable it within the existing CoreDNS process — just want to make sure we understand all our options.

@vthapar
>>The OpenShift DNS forwarding API explicitly disallows preempting our kubernetes plugin for cluster.local names

>Lighthouse doesn't preempt kubernetes. Only if kubernetes returns NXDOMAIN, we fallthrough to lighthouse.

All I meant is that the DNS forwarding API we have already won't support the use case as described. Hope that makes sense.

**Comment by aswinsuryan** [comment]
> @aswinsuryan thank you for the detailed background... you may well be correct that the approach I described has some blocking issues in practice. I'm hoping me or someone on the team can do some more careful analysis and prototyping soon. Do you agree in principle that if the problems you found could be resolved that a generic forwarding to a separately managed Lighthouse DNS server would be reasonable?

@ironcladlou 
Yes this would be an option that we are interested in , if we  could  address the issues.
> 
> To be clear, I'm not necessarily against the idea of carrying a patch for Lighthouse in-tree and then perhaps exposing some API to enable it within the existing CoreDNS process — just want to make sure we understand all our options.
> 
> @vthapar
> 
> > > The OpenShift DNS forwarding API explicitly disallows preempting our kubernetes plugin for cluster.local names
> 
> > Lighthouse doesn't preempt kubernetes. Only if kubernetes returns NXDOMAIN, we fallthrough to lighthouse.
> 
> All I meant is that the DNS forwarding API we have already won't support the use case as described. Hope that makes sense.

**Comment by aswinsuryan** [comment]
Lighthouse has enhanced use forward plugin and will now be authoritative for a separate Domain, supercluster.local, which will resolve services across clusters.
  Corefile: |
    supercluster.local:53 {
        forward . 10.10.10.10
    }
    .:53 {
        errors
        health
        log
        kubernetes cluster1.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }


Hence closing this issue.
